global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Claude Code metrics from the Prometheus exporter
  - job_name: 'claude-code'
    static_configs:
      - targets: ['172.27.224.41:9464']  # WSL host IP - update if needed
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Scrape node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']